/*
 * Copyright 2008 - 2013 HERAS-AF (www.herasaf.org)
 * Holistic Enterprise-Ready Application Security Architecture Framework
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.03 at 07:56:30 AM CEST 
//

package org.herasaf.xacml.core.context.impl;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlTransient;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for StatusDetailType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatusDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * See: <a href= "http://www.oasis-open.org/committees/tc_home.php?wg_abbrev=xacml#XACML20"> OASIS eXtensible Access
 * Control Markup Langugage (XACML) 2.0, Errata 29. January 2008</a> page 79, for further information.
 * 
 * @version 1.0
 * @author <i>generated</i>
 */
@XmlRootElement(name = "StatusDetail", namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")
@XmlType(name = "StatusDetailType", propOrder = { "content" })
public class StatusDetailType implements Serializable {
    private static final ObjectFactory OBJECT_FACTORY;
    private static final long serialVersionUID = 1L;
    @XmlAnyElement(lax = true)
    private List<Object> content;

    /**
     * Initializes the object factory.
     */
    static {
        OBJECT_FACTORY = new ObjectFactory();
    }

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list org.w3c.dom.Element, {@link Object }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * This method returns the {@link MissingAttributeDetailType}s contained in this {@link StatusDetailType}. It is now
     * allowed to add a new {@link MissingAttributeDetailType} with <code>getMissingAttributeDetails().add(...)</code>.
     * Use {@link #addMissingAttribute(MissingAttributeDetailType)} instead.
     * 
     * @return The {@link MissingAttributeDetailType}s contained in this {@link StatusDetailType}.
     */
    @XmlTransient
    public List<MissingAttributeDetailType> getMissingAttributeDetails() {
        List<MissingAttributeDetailType> missingAttributes = new ArrayList<MissingAttributeDetailType>();
        for (Object obj : content) {
            if (obj instanceof MissingAttributeDetailType) {
                missingAttributes.add((MissingAttributeDetailType) obj);
            }
        }
        return missingAttributes;
    }

    /**
     * Add a new {@link MissingAttributeDetailType} to this {@link StatusDetailType}.
     * 
     * @param missingAttribute
     *            The {@link MissingAttributeDetailType} to add.
     */
    public void addMissingAttribute(MissingAttributeDetailType missingAttribute) {
        content.add(OBJECT_FACTORY.createMissingAttributeDetail(missingAttribute));
    }
}
